services:
  spotify-tokens:
    container_name: spotify-tokens-container
    image: spotify-tokens:v4.3  # You can update the version as needed
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"  # Map the port specified in the environment variable
    restart: always
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REFRESH_TOKEN=${SPOTIFY_REFRESH_TOKEN}
      - PORT=${PORT}
      - REFERER=${REFERER}
      - ALLOWED_ORIGIN=${ALLOWED_ORIGIN}
