name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date +%Y.%m.%d.%H%M%S)" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag spotify-api:${{ env.TIMESTAMP }}

      - name: Create a new Git tag
        if: github.event_name == 'push'
        run: |
          git tag ${{ env.TIMESTAMP }}
          git push origin ${{ env.TIMESTAMP }}

      - name: Create a new release on GitHub
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ env.TIMESTAMP }}
          tag_name: ${{ env.TIMESTAMP }}
          body: |
            Automatic release of the Docker image.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
