name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag spotify-api:$(date +%Y%m%d%H%M%S)

      - name: Create a new release on GitHub
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.sha }}
          tag_name: v${{ github.run_number }}
          body: |
            Automatic release of the latest Docker image.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
